/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitadosIndexRouteImport } from './routes/invitados/index'
import { Route as InvitadosNuevoRouteImport } from './routes/invitados/nuevo'
import { Route as InvitadosIdEditarRouteImport } from './routes/invitados/$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitadosIndexRoute = InvitadosIndexRouteImport.update({
  id: '/invitados/',
  path: '/invitados/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitadosNuevoRoute = InvitadosNuevoRouteImport.update({
  id: '/invitados/nuevo',
  path: '/invitados/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitadosIdEditarRoute = InvitadosIdEditarRouteImport.update({
  id: '/invitados/$id/editar',
  path: '/invitados/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invitados/nuevo': typeof InvitadosNuevoRoute
  '/invitados/': typeof InvitadosIndexRoute
  '/invitados/$id/editar': typeof InvitadosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invitados/nuevo': typeof InvitadosNuevoRoute
  '/invitados': typeof InvitadosIndexRoute
  '/invitados/$id/editar': typeof InvitadosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invitados/nuevo': typeof InvitadosNuevoRoute
  '/invitados/': typeof InvitadosIndexRoute
  '/invitados/$id/editar': typeof InvitadosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/invitados/nuevo' | '/invitados/' | '/invitados/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/invitados/nuevo' | '/invitados' | '/invitados/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/invitados/nuevo'
    | '/invitados/'
    | '/invitados/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvitadosNuevoRoute: typeof InvitadosNuevoRoute
  InvitadosIndexRoute: typeof InvitadosIndexRoute
  InvitadosIdEditarRoute: typeof InvitadosIdEditarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitados/': {
      id: '/invitados/'
      path: '/invitados'
      fullPath: '/invitados/'
      preLoaderRoute: typeof InvitadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitados/nuevo': {
      id: '/invitados/nuevo'
      path: '/invitados/nuevo'
      fullPath: '/invitados/nuevo'
      preLoaderRoute: typeof InvitadosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitados/$id/editar': {
      id: '/invitados/$id/editar'
      path: '/invitados/$id/editar'
      fullPath: '/invitados/$id/editar'
      preLoaderRoute: typeof InvitadosIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvitadosNuevoRoute: InvitadosNuevoRoute,
  InvitadosIndexRoute: InvitadosIndexRoute,
  InvitadosIdEditarRoute: InvitadosIdEditarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
